# Generated by Django 4.1.2 on 2022-10-21 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0002_rename_product_cart_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='name',
            new_name='product',
        ),
    ]
